build:
  stage: build
  image: ghcr.io/foundry-rs/foundry:latest
  tags:
    - docker
  artifacts:
    untracked: true
  script:
    - pnpm install
    - forge soldeer install
    - forge build
    - forge test

build_container:
  stage: deploy
  image: docker:29.0.4
  tags:
    - dind
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    FOUNDRY_DISABLE_NIGHTLY_WARNING: "true"
  services:
    - docker:dind
  before_script:
    - docker info
    - export DOCKER_BUILDKIT=1
  script:
    - echo "$CI_REGISTRY_IMAGE:latest"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME