[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "./" }]
allow_paths = ["*", "/"]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
evm_version = "cancun"
solc = "0.8.28"
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
zkxsolla = "${ZKXSOLLA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"
 
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[dependencies]
eth-infinitism-account-abstraction = "0.8.0"
"@openzeppelin-contracts" = "5.4.0"
solady = "0.1.24"
forge-std = { version = "master-06-10-2025", git = "https://github.com/foundry-rs/forge-std", rev = "17a9b2398a7d629931dc66a168a098d051d53dc6" }
"@openzeppelin-contracts-upgradeable" = "5.5.0-rc.1"

[profile.lint]
lint_on_build = true
severity = ["high", "med", "low", "info"]
exclude_lints = [
    "pascal-case-struct",
    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-const",
    "screaming-snake-case-immutable"
]
